import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins(
  {
    weight: ["100", "200", "300", "400", "500"],
    subsets: ["latin"]
  }
)


export const metadata: Metadata = {
  title: "Grouping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
